pipelines:
    default:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/stay-hard/bitbucket-migration.git 
            - cd bitbucket-migration.git
            - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE"@github.com/Kendohopkins/bitbucket-migration.git